SHELL = /usr/bin/env bash

PANTABLELOGLEVEL ?= DEBUG
python ?= python
_python = PANTABLELOGLEVEL=$(PANTABLELOGLEVEL) $(python)
pandoc ?= pandoc
_pandoc = PANTABLELOGLEVEL=$(PANTABLELOGLEVEL) $(pandoc)
PYTESTARGS ?= -n auto
# for `uv version --bump`, valid options are: major, minor, patch
PART ?= patch

pandocArgs = --toc -M date="`date "+%B %e, %Y"`" --filter=pantable --wrap=none

RSTs = CHANGELOG.rst README.rst

# Main Targets #################################################################

.PHONY: test docs-all docs html epub dot clean Clean

all: dot
	$(MAKE) test docs-all

test:
	rm -f .coverage*
	$(_python) -m coverage run -m pytest -vv $(PYTESTARGS) tests
coverage: test
	coverage combine
	coverage report
	coverage html

docs-all: docs html epub
docs: $(RSTs)
html: dist/docs/
epub: dist/epub/pantable.epub

dot:
	cd docs/dot; $(MAKE)

clean:
	rm -f .coverage* docs/pantable*.rst docs/modules.rst docs/setup.rst setup.py
	rm -rf htmlcov pantable.egg-info .cache .idea dist docs/_build \
		docs/_static docs/_templates .ipynb_checkpoints .mypy_cache \
		.pytest_cache .tox
	find . -type f -name "*.py[co]" -delete \
		-or -type d -name "__pycache__" -delete
Clean: clean
	rm -f $(RSTs)

# maintenance ##################################################################

.PHONY: build bump
build:
	rm -rf dist
	uv build

print-%:
	$(info $* = $($*))

# docs #########################################################################

README.rst: docs/README.md
	printf \
		"%s\n\n" \
		".. This is auto-generated from \`$<\`. Do not edit this file directly." \
		> $@
	cd $(<D); \
	$(_pandoc) $(pandocArgs) $(<F) -V title='pantable Documentation' -s -t rst \
		>> ../$@

%.rst: %.md
	printf \
		"%s\n\n" \
		".. This is auto-generated from \`$<\`. Do not edit this file directly." \
		> $@
	$(_pandoc) $(pandocArgs) $< -s -t rst >> $@

dist/docs/:
	sphinx-build -E -b dirhtml docs dist/docs
# depends on docs as the api doc is built there
# didn't put this in tox as we should build this once every release
# TODO: consider put this in tox and automate it in GH Actions
dist/epub/pantable.epub: docs
	sphinx-build -E -b epub docs dist/epub
# the badges and dots has svg files that LaTeX complains about
# dist/pantable.pdf: docs
# 	sphinx-build -E -b latex docs dist/pdf
# 	cd dist/pdf; make
# 	mv dist/pdf/pantable.pdf dist

# releasing ####################################################################

# bump version, commit, tag, and push; pushing the tag triggers the release workflow
bump:
	uv version --bump $(PART) --frozen
	git commit -am "Bump version: $$(uv version --short)"
	git tag -a "v$$(uv version --short)" -m "v$$(uv version --short)"
	git push --follow-tags
